# This file is auto-generated by src/generate_pocket_firmware_details.py
def pocket_firmware_details(): return {
    "url": "https://assets.analogue.co/firmware/42cd214fd21111f60390167ce8cf1ff9/pocket_firmware_2_5.bin",
    "version": "2.5",
    "file": "pocket_firmware_2_5.bin",
    "md5": "42cd214fd21111f60390167ce8cf1ff9",
    "size": 54.5
}
