# This file is auto-generated by src/generate_pocket_firmware_details.py
def pocket_firmware_details(): return {
    "url": "https://assets.analogue.co/firmware/63ff5777994cad18eb8faedb6732bd83/pocket_firmware_2_2.bin",
    "version": "2.2",
    "file": "pocket_firmware_2_2.bin",
    "md5": "63ff5777994cad18eb8faedb6732bd83",
    "size": 54.5
}
