# File auto-generated by src/generate_pocket_firmware_details.py
def pocket_firmware_details(): return {
    "url": "https://assets.analogue.co/firmware/bce124b1193d7e35d66f41abbca966e9/pocket_firmware_2_0.bin",
    "version": "2.0",
    "file": "pocket_firmware_2_0.bin",
    "md5": "bce124b1193d7e35d66f41abbca966e9",
    "size": 54.5
}
